"""fix database again

Revision ID: 5afe6348060e
Revises: d011b54bca7f
Create Date: 2026-08-15 16:00:26.771877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5afe6348060e'
down_revision: Union[str, Sequence[str], None] = 'd011b54bca7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('error_logs',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('object_id', sa.CHAR(length=36), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_error_logs_event', 'error_logs', ['event_type', 'object_id'], unique=False)
    op.create_index('idx_autofill_rules_match', 'autofill_rules', ['match_type', 'match_value'], unique=False, mysql_length={'match_value': 255})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_autofill_rules_match', table_name='autofill_rules', mysql_length={'match_value': 255})
    op.drop_index('idx_error_logs_event', table_name='error_logs')
    op.drop_table('error_logs')
    # ### end Alembic commands ###
