"""create table

Revision ID: dfe7b84deae7
Revises: 
Create Date: 2026-08-14 17:10:29.711081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfe7b84deae7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vault_items',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('platform_type', sa.Enum('web', 'desktop_app', 'other'), nullable=False),
    sa.Column('platform_identifier', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password_encrypted', sa.VARBINARY(length=512), nullable=False),
    sa.Column('password_nonce', sa.VARBINARY(length=32), nullable=False),
    sa.Column('totp_secret_encrypted', sa.VARBINARY(length=512), nullable=True),
    sa.Column('totp_secret_nonce', sa.VARBINARY(length=32), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('notes_encrypted', sa.BLOB(), nullable=True),
    sa.Column('notes_nonce', sa.VARBINARY(length=32), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('favorite', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vault_meta',
    sa.Column('id', sa.SmallInteger(), autoincrement=False, nullable=False),
    sa.Column('kdf_algorithm', sa.String(length=32), server_default='argon2id', nullable=False),
    sa.Column('kdf_salt', sa.VARBINARY(length=64), nullable=False),
    sa.Column('kdf_memory_cost', sa.Integer(), nullable=False),
    sa.Column('kdf_time_cost', sa.Integer(), nullable=False),
    sa.Column('kdf_parallelism', sa.Integer(), nullable=False),
    sa.Column('verifier_hash', sa.VARBINARY(length=256), nullable=False),
    sa.Column('verifier_salt', sa.VARBINARY(length=64), nullable=False),
    sa.Column('schema_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('id = 1', name='ck_vault_meta_single_row'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('autofill_rules',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('vault_item_id', sa.CHAR(length=36), nullable=False),
    sa.Column('match_type', sa.Enum('domain', 'window_title_regex'), nullable=False),
    sa.Column('match_value', sa.String(length=512), nullable=False),
    sa.Column('field_role', sa.Enum('username', 'password', 'otp'), nullable=False),
    sa.Column('priority', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['vault_item_id'], ['vault_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('password_history',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('vault_item_id', sa.CHAR(length=36), nullable=False),
    sa.Column('password_encrypted', sa.VARBINARY(length=512), nullable=False),
    sa.Column('password_nonce', sa.VARBINARY(length=32), nullable=False),
    sa.Column('changed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vault_item_id'], ['vault_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('password_history')
    op.drop_table('autofill_rules')
    op.drop_table('vault_meta')
    op.drop_table('vault_items')
    # ### end Alembic commands ###
